### PR TITLE
Support for auto-completion of storage pool related APIs

### PR DESCRIPTION
**Pull request by Pearl1594**
This PR attempts to fix: https://github.com/apache/cloudstack-cloudmonkey/issues/98 

For most APIs where id points to storage pools, the auto-completion does not work i.e., it doesn't find the list of storage pools. Few examples of this include:
updateStorageCapabilities, enableStorageMaintenance, cancelStorageMaintenance, etc

Similarly, APIs which have storageid as arguments, do not auto-complete to list the available storage pools.
for example: list volumes storageid=...

### CODE REVIEW

**Review by DaanHoogland — APPROVED** [review]
looks good @Pearl1594, is this ready for test?

**Comment by Pearl1594** [comment]
Yes @DaanHoogland this is ready for testing.

**Review by DaanHoogland — APPROVED** [review]
tested remotely against lab environments

**Review by borisstoyanov — APPROVED** [review]
Screenshot 2023-02-08 at 15 39 11
LGTM

**Pull request merged**
