### PR TITLE
signatureversion and backward compatibility

### PR DESCRIPTION
**Pull request by ntavares**
Provide signatureversion as config.option for backward compatibility;
Follow specification: only provide signatureversion=&expires= in URL if signatureversion=3
http://docs.cloudstack.apache.org/en/latest/dev.html?highlight=signatureversion

PS: We want signatureversion to be an integer

### CODE REVIEW

**Comment by bhaisaab** [comment]
@ntavares looks good to me, though it fails to apply on master. Can you please rebase against master and send a patch that would apply cleanly? Thanks.

**Comment by ntavares** [comment]
@bhaisaab What a mess ahah... My branch was fresh, I believe I last apache' commit was from my pull request.. not sure what happened here and it got worse when I tried to rebase... maybe it was OK the first time, I'm not an experienced git user... can you try again, now?

**Comment by ntavares** [comment]
Hopefully this is properly rebased now.

**Comment by ntavares** [comment]
@bhaisaab Can you please reject/close this one, it got too messy :-)

**Comment by bhaisaab** [comment]
@ntavares okay, I'll help review the other one

**Pull request closed without merging**
