### PR TITLE
vendor: update vendor and gomod

### PR DESCRIPTION
**Pull request by rohityadavcloud**
Revert changes from previous commit on
vendor/github.com/chzyer/readline/complete.go

### CODE REVIEW

**Comment by rohityadavcloud** [comment]
Regression fixed (reverted following) + go mod updates:
Screenshot 2023-03-02 at 3 28 23 PM

**Comment by borisstoyanov** [comment]
+1 will test it out quickly and merge

**Review by borisstoyanov — APPROVED** [review]
Manually tested, cmk seems to be functioning good, did not see any affected areas

**Comment by rohityadavcloud** [comment]
The regression this fixes is the parameter autocompletion, where it includes resource name as in:
```
templateid=99bcd10d-eaa4-4ad6-8169-7cf204fbc0b3 (Rocky 9 x64)
```

With this fix, the autocompletion ignores the stuff starting with parenthesis:
```
templateid=99bcd10d-eaa4-4ad6-8169-7cf204fbc0b3
```

**Pull request merged**
